### ISSUE TITLE
videoUpload endpoints doesn't seem to be working

### ISSUE THREAD

**Issue by lsetiawan** [cormorack/cava-media#32]
## Overview

The videoUpload endpoints and its child routes doesn't seem to be working

## videoUpload

https://api-development.ooica.net/media/videoUpload

![Screenshot from 2021-02-12 14-35-04](https://user-images.githubusercontent.com/17802172/107829895-8237e300-6d3f-11eb-98e1-f5b5dd3f8c0c.png)

<details>
<summary>Error logs</summary>

```
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382925658Z 2021-02-12 22:34:41.382 ERROR --- [io-8080-exec-10] o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/videoUpload] due to exception [Could not resolve view with name 'index' in servlet with name 'grailsDispatcherServlet']
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382954421Z 
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382958072Z javax.servlet.ServletException: Could not resolve view with name 'index' in servlet with name 'grailsDispatcherServlet'
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382961372Z 	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1352)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382964648Z 	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1118)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382967632Z 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1057)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382970517Z 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382973495Z 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382976391Z 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382979286Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382982141Z 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382985102Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382987948Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382990875Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382993726Z 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382996599Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.382999494Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383002380Z 	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383005350Z 	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383008201Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383011149Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383014771Z 	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383017762Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383020660Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383033954Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383036675Z 	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383039210Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383041741Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383044254Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383046784Z 	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383049308Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383051841Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383055208Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383057784Z 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383060402Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383062944Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383065461Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383067990Z 	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383070627Z 	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383073171Z 	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383075704Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383078241Z 	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383081104Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383083658Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383086244Z 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383088889Z 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383091569Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383096948Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383099584Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383102109Z 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383104589Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383107137Z 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383109657Z 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383112157Z 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383114646Z 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383117134Z 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383119634Z 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383122133Z 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383124606Z 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383127128Z 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383129678Z 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383132201Z 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383134697Z 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383137184Z 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383139992Z 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383142513Z 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383145008Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383147512Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383149997Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383152511Z 	at java.base/java.lang.Thread.run(Thread.java:834)
cava-media-85b76c7465-4rjd4 cava-media 2021-02-12T22:34:41.383155088Z 
```
</details>

## videoUpload/uploadVideo

https://api-development.ooica.net/media/videoUpload/uploadVideo

![Screenshot from 2021-02-12 14-39-21](https://user-images.githubusercontent.com/17802172/107830169-23bf3480-6d40-11eb-92aa-b40ae0c3b55a.png)

There doesn't seem to be an error log on the backend found.

**Comment by sdthomas69** [comment]
The correct path is /media/videoUpload/videoForm

**Comment by sdthomas69** [comment]
The endpoint on the documentation page (/videoUpload/uploadVideo) is just for posting.  But it could be named a little better...
